(
 ("apt" (:command "apt")
        (:search "apt search")
        (:list "apt list")
        (:install "sudo apt install -y")
        (:remove "sudo apt uninstall -y")
        (:update "sudo apt update && sudo apt upgrade"))
 ("dnf" (:command "dnf")
        (:search "dnf search")
        (:list "dnf list")
        (:install "sudo dnf install -y")
        (:remove "sudo dnf uninstall -y")
        (:update "sudo dnf update"))
 ("pacman" (:command "pacman")
           (:search "pacman -Ssq")
           (:list "pacman -Q")
           (:install "sudo pacman -S --noconfirm")
           (:remove "sudo pacman -R --noconfirm")
           (:update "sudo pacman -Syu --noconfirm"))
 ("paru" (:command "paru")
         (:search "paru -Ssq")
         (:list "paru -Q")
         (:install "paru -S --noconfirm")
         (:remove "paru -R --noconfirm")
         (:update "paru -Syu --noconfirm"))
 ("xbps" (:command "xbps-query")
         (:search "xbps-query -Rs")
         (:list "xbps-query -s")
         (:install "sudo xbps-install -S")
         (:remove "sudo xbps-remove -R")
         (:update "sudo xbps-install -Su"))
 ("flatpak" (:command "flatpak")
            (:search "flatpak search")
            (:list "flatpak list")
            (:install "sudo flatpak install")
            (:remove "sudo flatpak uninstall")
            (:update "sudo flatpak update"))
 ("snap" (:command "snap")
         (:search "snap find")
         (:list "snap list")
         (:install "snap install")
         (:remove "snap remove")
         (:update "snap refresh"))
 ("brew" (:command "brew")
         (:search "brew search")
         (:list "brew list")
         (:install "brew install")
         (:remove "brew uninstall")
         (:update "brew upgrade"))
 ("cask" (:command "brew")
         (:search "brew search --cask")
         (:list "brew list --cask")
         (:install "brew install --cask")
         (:remove "brew uninstall --cask")
         (:update "brew upgrade --cask"))
 )
